# Generated by Django 2.0.2 on 2018-03-12 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('clases', '0001_initial'),
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiquetas.Etiqueta')),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Clase')),
            ],
        ),
    ]
