# Generated by Django 2.0.2 on 2018-04-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20180424_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talle',
            field=models.CharField(choices=[('P', 'Pequenho'), ('M', 'Mediano'), ('G', 'Grande')], default='P', max_length=3),
            preserve_default=False,
        ),
    ]
