# Generated by Django 2.0.2 on 2018-04-26 01:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_producto_talle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(choices=[(Decimal('0.05'), '5%'), (Decimal('0.10'), '10%'), (Decimal('0.0'), 'Exentas')], decimal_places=2, max_digits=3),
        ),
    ]
