# Generated by Django 2.0.2 on 2018-05-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20180425_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='ruc',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
