# Generated by Django 2.0.2 on 2018-05-10 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20180509_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
