# Generated by Django 2.0.2 on 2018-05-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_compracabecera_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetalle',
            old_name='id_cab_compra',
            new_name='compra',
        ),
    ]
