# Generated by Django 2.0.2 on 2018-05-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20180509_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetalle',
            old_name='id_producto',
            new_name='producto',
        ),
    ]
