# Generated by Django 2.0.2 on 2018-05-13 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_auto_20180513_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventacabecera',
            old_name='factura',
            new_name='talonario_factura',
        ),
        migrations.RenameField(
            model_name='ventadetalle',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='ventadetalle',
            old_name='id_cab_venta',
            new_name='venta',
        ),
        migrations.AddField(
            model_name='ventacabecera',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ventacabecera',
            name='nro_factura',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ventacabecera',
            name='total_iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventacabecera',
            name='total_iva_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventacabecera',
            name='total_iva_5',
            field=models.IntegerField(default=0),
        ),
    ]
