# Generated by Django 2.0.2 on 2018-05-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_remove_ventacabecera_monto_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc_cliente',
            field=models.CharField(max_length=15),
        ),
    ]
