# Generated by Django 2.0.2 on 2018-05-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_auto_20180517_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacabecera',
            name='nro_factura_numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventacabecera',
            name='nro_factura_punto_emision',
            field=models.CharField(default='', max_length=10),
        ),
    ]
