# Generated by Django 2.0.2 on 2018-05-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_auto_20180519_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc_cliente',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
