# Generated by Django 2.0.2 on 2018-05-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_auto_20180519_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventadetalle',
            old_name='precio',
            new_name='monto_10',
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='detalle',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='monto_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='monto_exento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO')], max_length=2),
        ),
    ]
