# Generated by Django 2.0.2 on 2018-05-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_ventadetalle_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacabecera',
            name='total_iva_exentas',
            field=models.IntegerField(default=0),
        ),
    ]
