# Generated by Django 2.0.2 on 2018-05-31 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_auto_20180527_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_cab_venta',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_cuenta',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
