# Generated by Django 2.0.2 on 2018-06-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_auto_20180530_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacabecera',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO')], default='A', max_length=1),
        ),
    ]
