# Generated by Django 2.0.2 on 2018-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_ventacabecera_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacabecera',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO')], default='A', max_length=2),
        ),
    ]
