# Generated by Django 2.0.2 on 2018-06-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_auto_20180601_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('ENT', 'ENTRADA'), ('SAL', 'SALIDA')], default='ENT', max_length=3)),
            ],
        ),
    ]
