# Generated by Django 2.0.2 on 2018-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_auto_20180606_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioncaja',
            name='tipo_transaccion',
            field=models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], default='ENT', max_length=3),
        ),
    ]
