# Generated by Django 2.0.2 on 2018-06-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0027_auto_20180607_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioncaja',
            name='tipo_transaccion',
            field=models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], default='ENT', max_length=7),
        ),
    ]
