# Generated by Django 2.0.2 on 2018-06-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_auto_20180607_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='ruc_proveedor',
            field=models.CharField(default='', max_length=15),
        ),
    ]
