# Generated by Django 2.0.2 on 2018-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_compracabecera_ruc_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacabecera',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque')], default='Efectivo', max_length=8),
        ),
    ]
