# Generated by Django 2.0.2 on 2018-06-10 00:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0030_ventacabecera_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque')], default='', max_length=8)),
                ('monto', models.IntegerField(default=0)),
                ('tarjeta', models.CharField(choices=[('INFONET-DEBITO', 'INFONET-DEBITO'), ('INFONET-CREDITO', 'INFONET-CREDITO')], default='', max_length=25)),
                ('nro_autorizacion', models.IntegerField(default=0)),
                ('ultimos_tarjeta', models.IntegerField(default=0)),
                ('banco', models.CharField(default='', max_length=150, null=True)),
                ('nro_cuenta', models.CharField(default='', max_length=150, null=True)),
                ('librador', models.CharField(default='', max_length=150, null=True)),
                ('serie_cheque', models.CharField(default='', max_length=150, null=True)),
                ('nro_cheque', models.CharField(default='', max_length=150, null=True)),
                ('fecha_emision', models.DateField(default=datetime.date.today, null=True)),
                ('fecha_venc', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ventacabecera',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.VentaCabecera'),
        ),
    ]
