# Generated by Django 2.0.2 on 2018-06-10 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_auto_20180609_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_emision',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_venc',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='librador',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nro_autorizacion',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nro_cheque',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nro_cuenta',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='serie_cheque',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tarjeta',
            field=models.CharField(blank=True, choices=[('INFONET-DEBITO', 'INFONET-DEBITO'), ('INFONET-CREDITO', 'INFONET-CREDITO')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='pago',
            name='ultimos_tarjeta',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.VentaCabecera'),
        ),
    ]
