# Generated by Django 2.0.2 on 2018-06-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_auto_20180610_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='nro_autorizacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='ultimos_tarjeta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
