# Generated by Django 2.0.2 on 2018-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0033_auto_20180611_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_venc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
