# Generated by Django 2.0.2 on 2018-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0034_auto_20180611_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='nro_autorizacion',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='ultimos_tarjeta',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
