# Generated by Django 2.0.2 on 2018-06-16 20:22

from django.db import migrations

def create_producto_cuenta(apps, schema_editor):
    Producto = apps.get_model("tienda", "Producto")
    existe = Producto.objects.filter(codigo='CUENTA').exists()
    if not existe:
        producto_cuenta = Producto()
        producto_cuenta.codigo = 'CUENTA'
        producto_cuenta.iva = '0.10'
        producto_cuenta.nombre = 'Cuenta'
        producto_cuenta.descripcion = 'Cuenta'
        producto_cuenta.estado = 'A'
        producto_cuenta.control_stock = False
        producto_cuenta.save()


def delete_producto_cuenta(apps, schema_editor):
    Producto = apps.get_model("tienda", "Producto")
    Producto.objects.filter(codigo='CUENTA').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0036_auto_20180611_1609'),
    ]

    operations = [
        migrations.RunPython(create_producto_cuenta, reverse_code=delete_producto_cuenta)
    ]
