# Generated by Django 2.0.2 on 2018-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0038_auto_20180616_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetalle',
            old_name='producto',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='compradetalle',
            old_name='cantidad',
            new_name='monto_10',
        ),
        migrations.RenameField(
            model_name='compradetalle',
            old_name='precio',
            new_name='monto_5',
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='monto_exento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='ruc',
            field=models.CharField(max_length=9),
        ),
    ]
