# Generated by Django 2.0.2 on 2018-06-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0039_auto_20180617_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.CompraCabecera'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='detalle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO')], default='A', max_length=2),
        ),
    ]
