# Generated by Django 2.0.2 on 2018-06-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0040_auto_20180617_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacabecera',
            name='total_grav_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventacabecera',
            name='total_grav_5',
            field=models.IntegerField(default=0),
        ),
    ]
