# Generated by Django 2.0.2 on 2018-06-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0042_auto_20180618_0000'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operacioncaja',
            index=models.Index(fields=['fecha', 'tipo_transaccion'], name='tienda_oper_fecha_99a833_idx'),
        ),
    ]
