# Generated by Django 2.0.2 on 2018-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0043_auto_20180620_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='total_grav_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compracabecera',
            name='total_grav_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compracabecera',
            name='total_grav_exentas',
            field=models.IntegerField(default=0),
        ),
    ]
