# Generated by Django 2.0.2 on 2018-06-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0044_auto_20180623_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_cheque',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_efectivo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_efectivo_abonado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_efectivo_vuelto',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_tarjeta',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='pago_cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='pago_efectivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='pago_tarjeta',
            field=models.BooleanField(default=False),
        ),
    ]
