# Generated by Django 2.0.2 on 2018-07-02 01:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0046_ventacabecera_credito_plazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nro_recibo', models.CharField(max_length=32)),
                ('pago_efectivo', models.BooleanField(default=False)),
                ('pago_tarjeta', models.BooleanField(default=False)),
                ('pago_cheque', models.BooleanField(default=False)),
                ('monto', models.IntegerField(blank=True, default=0)),
                ('monto_efectivo', models.IntegerField(blank=True, default=0)),
                ('monto_efectivo_abonado', models.IntegerField(blank=True, default=0)),
                ('monto_efectivo_vuelto', models.IntegerField(blank=True, default=0)),
                ('monto_tarjeta', models.IntegerField(blank=True, default=0)),
                ('monto_cheque', models.IntegerField(blank=True, default=0)),
                ('tarjeta', models.CharField(blank=True, choices=[('INFONET-DEBITO', 'INFONET-DEBITO'), ('INFONET-CREDITO', 'INFONET-CREDITO')], default='', max_length=25, null=True)),
                ('nro_autorizacion', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('ultimos_tarjeta', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('banco', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('nro_cuenta', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('librador', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('serie_cheque', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('nro_cheque', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_venc', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ventacabecera',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO'), ('P', 'PENDIENTE')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='recibo',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.VentaCabecera'),
        ),
    ]
