# Generated by Django 2.0.2 on 2018-07-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0046_ventacabecera_credito_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacabecera',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO'), ('P', 'PENDIENTE')], default='A', max_length=2),
        ),
    ]
