# Generated by Django 2.0.2 on 2018-07-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0047_auto_20180702_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=150),
        ),
    ]
