# Generated by Django 2.0.2 on 2018-07-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0048_recibo_nombre_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('cliente_delete', 'Dar de baja cliente'), ('cliente_create', 'Crear cliente'), ('cliente_update', 'Editar cliente'), ('clientes_list', 'Listar cliente'))},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': (('factura_delete', 'Dar de baja factura'), ('factura_create', 'Crear factura'), ('factura_update', 'Editar factura'), ('factura_list', 'Listar factura'))},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('producto_delete', 'Dar de baja producto'), ('producto_create', 'Crear producto'), ('producto_update', 'Editar producto'), ('producto_list', 'Listar producto'))},
        ),
    ]
