# Generated by Django 2.0.2 on 2018-07-06 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0049_auto_20180704_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacabecera',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
