# Generated by Django 2.0.2 on 2018-02-26 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('imagen', models.ImageField(upload_to='media_root', verbose_name='Imagen')),
                ('ficha', models.FileField(upload_to='media_root')),
                ('especialidad', models.CharField(max_length=50)),
                ('salario', models.IntegerField(default=0)),
            ],
        ),
    ]
