# Generated by Django 2.0.2 on 2018-03-13 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fotocopia_ceudla',
            new_name='fotocopia_cedula',
        ),
    ]
