# Generated by Django 2.0 on 2018-02-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ficha',
            field=models.FileField(default=2, upload_to='media_root'),
            preserve_default=False,
        ),
    ]
