# Generated by Django 2.0.2 on 2018-05-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='id_grupo',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='diahora',
            old_name='id_grupo',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='diahora',
            old_name='hora',
            new_name='hora_fin',
        ),
        migrations.RenameField(
            model_name='etiquetagrupo',
            old_name='id_grupo',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='id_grupo',
            new_name='grupo',
        ),
        migrations.RemoveField(
            model_name='diahora',
            name='dia',
        ),
        migrations.AddField(
            model_name='diahora',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diahora',
            name='hora_inicio',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diahora',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diahora',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diahora',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diahora',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diahora',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diahora',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('id_clase', 'id_profesor')},
        ),
    ]
