# Generated by Django 2.0.2 on 2018-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('escuela', '0002_auto_20180502_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diahora',
            name='grupo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='hora_fin',
            field=models.TimeField(default='8:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='hora_inicio',
            field=models.TimeField(default='8:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('id_clase', 'id_profesor', 'hora_inicio', 'hora_fin', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo')},
        ),
        migrations.DeleteModel(
            name='DiaHora',
        ),
    ]
