# Generated by Django 2.0.2 on 2018-05-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20180505_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set(),
        ),
    ]
