# Generated by Django 2.0.2 on 2018-05-27 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_auto_20180506_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='id_alumno',
            new_name='alumno',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='comentario',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_fin',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inicio',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
