# Generated by Django 2.0.2 on 2018-05-31 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_auto_20180530_2027'),
        ('escuela', '0007_auto_20180530_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimiento', models.DateField(default=datetime.date.today)),
                ('monto', models.IntegerField(default=0)),
                ('monto_pagado', models.IntegerField(default=0)),
                ('pagado', models.BooleanField(default=False)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.VentaDetalle')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('IN', 'INACTIVO')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.Inscripcion'),
        ),
    ]
