# Generated by Django 2.0.2 on 2018-06-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0010_auto_20180531_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'permissions': (('inscripcion_baja', 'Dar de baja inscripcion'),)},
        ),
    ]
