# Generated by Django 2.0.2 on 2018-06-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0012_remove_clase_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='id_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='escuela.Clase'),
        ),
    ]
