# Generated by Django 2.0.2 on 2018-07-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0013_auto_20180601_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
