# Generated by Django 2.0.2 on 2018-07-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0014_cuenta_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
