# Generated by Django 2.0.2 on 2018-07-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0016_auto_20180703_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'permissions': (('clase_delete', 'Dar de baja clase'), ('clase_create', 'Crear clase'), ('clase_update', 'Editar clase'), ('clase_list', 'Listar clase'))},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'permissions': (('cuenta_list', 'Listar cuenta'), ('cuenta_update', 'Editar cuenta'), ('cuenta_delete', 'Dar de baja cuenta'))},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'permissions': (('grupo_delete', 'Dar de baja grupo'), ('grupos_create', 'Crear grupo'), ('grupos_update', 'Editar grupo'), ('grupos_list', 'Listar grupo'))},
        ),
    ]
