# Generated by Django 2.0.2 on 2018-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='ficha',
            field=models.FileField(upload_to='media_root', verbose_name='Ficha médica'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ficha_inscripcion',
            field=models.FileField(upload_to='media_root', verbose_name='Ficha de inscripción'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(upload_to='media_root', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fotocopia_cedula',
            field=models.ImageField(blank=True, null=True, upload_to='media_root', verbose_name='Fotocopia de Cédula'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
