# Generated by Django 2.0.2 on 2018-05-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default='Profesor', max_length=50, null=True),
        ),
    ]
