# Generated by Django 2.0.2 on 2018-05-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180506_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='ficha',
            field=models.FileField(blank=True, null=True, upload_to='media_root', verbose_name='Ficha médica'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ficha_inscripcion',
            field=models.FileField(blank=True, null=True, upload_to='media_root', verbose_name='Ficha de inscripción'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media_root', verbose_name='Foto'),
        ),
    ]
