# Generated by Django 2.0.2 on 2018-05-31 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_auto_20180530_2027'),
        ('main', '0007_auto_20180528_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='id_persona',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
