# Generated by Django 2.0.2 on 2018-07-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180624_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'permissions': (('alumno_list', 'Listar alumno'), ('alumno_create', 'Crear alumno'), ('alumno_update', 'Editar alumno'), ('alumno_delete', 'Dar de baja alumno'))},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': (('empleado_delete', 'Dar de baja empleado'), ('empleado_create', 'Crear empleado'), ('empleado_update', 'Editar empleado'))},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'permissions': (('profesor_delete', 'Dar de baja empleado'), ('profesor_create', 'Crear profesor'), ('profesor_update', 'Editar profesor'))},
        ),
        migrations.AlterModelOptions(
            name='titular',
            options={'permissions': (('titular_list', 'Listar titular'), ('titular_create', 'Crear titular'), ('titular_update', 'Editar titular'), ('titular_delete', 'Dar de baja titular '))},
        ),
    ]
